// Autogenerated using npm run gen EditKeg
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function EditKeg(){
  return (
    <Main>
      <h1>EditKeg Component Created Successfully</h1>
    </Main>
  );
}

export default EditKeg;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import EditKeg from './EditKeg';
* <EditKeg/>
*/


