// Autogenerated using npm run gen Header
import styled from 'styled-components';
import { Link } from 'react-router-dom';

function Header(){
  return (
    <Main>
      <Link to='/'>Home</Link>
    </Main>
  );
}

export default Header;

const Main = styled.div`

`;

/*
* Copy to other files
* import Header from './Header';
* <Header/>
*/
