// Autogenerated using npm run gen Header
/*
* Copy to other files
* import Header from './Header';
* <Header/>
*/
import styled from 'styled-components';
import { Link } from 'react-router-dom';

function Header(){
  return (
    <Main>
      <div className="row">
        <div className="col-md-1"><Link to='/'>Home</Link></div>
        <div className="col-md-2"><Link to='/newkeg'>Add New Keg</Link></div>
      </div>
    </Main>
  );
}

export default Header;

const Main = styled.div`

`;
