// Autogenerated using npm run gen Inventory
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function Inventory(){
  return (
    <Main>
      <h1>Inventory Component Created Successfully</h1>
    </Main>
  );
}

export default Inventory;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import Inventory from './Inventory';
* <Inventory/>
*/


