// Autogenerated using npm run gen Inventory
/*
* Copy to other files
* import Inventory from './Inventory';
* <Inventory/>
*/
import styled from 'styled-components';
import KegDetail from './KegDetail';
// import { Link, Switch, Route } from 'react-router-dom';

function Inventory(props){

  return (
    <Main>
      <Title clasName="container">Keg Inventory</Title>
      {props.kegList.map((keg, index) =>
        <KegDetail
          name={keg.name}
          brewer={keg.brewer}
          description={keg.description}
          abv={keg.abv}
          price={keg.price}
          remaining={keg.remaining}
          id={index}
          key={index}/>
      )}
    </Main>
  );


}

Inventory.propTypes = {
kegList: PropTypes.array,
};

export default Inventory;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

const Title = styled.h1`
color: white;
text-align: center;
`;
