// Autogenerated using npm run gen KegDetail
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegDetail(){
  return (
    <Main>
      <h1>KegDetail Component Created Successfully</h1>
    </Main>
  );
}

export default KegDetail;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import KegDetail from './KegDetail';
* <KegDetail/>
*/


