// Autogenerated using npm run gen KegEdit
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegEdit(){
  return (
    <Main>
      <h1>KegEdit Component Created Successfully</h1>
    </Main>
  );
}

export default KegEdit;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import KegEdit from './KegEdit';
* <KegEdit/>
*/
