// Autogenerated using npm run gen KegSell
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegSell(){
  return (
    <Main>
      <h1>KegSell Component Created Successfully</h1>
    </Main>
  );
}

export default KegSell;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import KegSell from './KegSell';
* <KegSell/>
*/


