// Autogenerated using npm run gen KegWarning
/*
* Copy to other files
* import KegWarning from './KegWarning';
* <KegWarning/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegWarning(props){

  return (
    <Main className="container">
      <Keg className="card">
        <Name className="card-header">Warning {props.name} is low on pints please restock.</Name>
        <ul className="list-group list-group-flush">
          <Details className="list-group-item">Brewer: {props.brewer}</Details>
          <Details className="list-group-item">Desc: {props.description}</Details>
          <Details className="list-group-item">ABV: {props.abv}</Details>
          <Details className="list-group-item">Price: ${props.price}</Details>
          <Details className="list-group-item">In-Stock: {props.remaining} pints</Details>
        </ul>
        <div className="card-footer">
          <div className="row">
            <div className="col-md-2">
              <Button className="btn btn-dark btn-sm" onClick={handleClickSellPints}>Sell a Pint</Button>
            </div>
            <div className="col-md-2">
              <Button className="btn btn-dark btn-sm" onClick={handleRestockKeg}>Restock Keg</Button>
            </div>
          </div>
        </div>
      </Keg>
    </Main>
  );

  function handleClickSellPints()
  {
    props.onClickSellPints(props.id,1);
  }

  function handleRestockKeg()
  {
    props.onClickRestockKeg(props.id,1);
  }
}

KegWarning.propTypes = {
  name: PropTypes.string,
  brewer: PropTypes.string,
  description: PropTypes.string,
  abv: PropTypes.string,
  price: PropTypes.string,
  remaining: PropTypes.string,
  id: PropTypes.number,
  onClickSellPints: PropTypes.func,
  onClickRestockKeg: PropTypes.func,
};

export default KegWarning;

const Main = styled.div`

`;

const Keg = styled.div`
text-align: left;
background-color: red;
color: black;
padding: 16px;
padding-left: 32px;
`;

const Name = styled.h4`
test-align: center;
`;

const Details = styled.li`
`;

const Button = styled.button`

`;
