// Autogenerated using npm run gen KegWarning
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegWarning(){
  return (
    <Main>
      <h1>KegWarning Component Created Successfully</h1>
    </Main>
  );
}

export default KegWarning;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import KegWarning from './KegWarning';
* <KegWarning/>
*/


