// Autogenerated using npm run gen KegWarning
/*
* Copy to other files
* import KegWarning from './KegWarning';
* <KegWarning/>
*/
import PropTypes from 'prop-types';
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function KegWarning(props){

  return (
    <Main>
      <Keg>
        <Name>{props.name}
          <ul>
            <Details>Brewer: {props.brewer}</Details>
            <Details>Desc: {props.description}</Details>
            <Details>ABV: {props.abv}</Details>
            <Details>Price: ${props.price}</Details>
            <Details>In-Stock: {props.remaining} pints</Details>
            <Button className="btn btn-dark btn-sm" onClick={handleClickSellPints}>Sell a Pint</Button>
          </ul>
        </Name>
      </Keg>
    </Main>
  );

  function handleClickSellPints()
  {
    props.onClickSellPints(props.id);
  }
}

KegWarning.propTypes = {
  name: PropTypes.string,
  brewer: PropTypes.string,
  description: PropTypes.string,
  abv: PropTypes.string,
  price: PropTypes.string,
  remaining: PropTypes.string,
  id: PropTypes.number,
  onClickSellPints: PropTypes.func
};

export default KegWarning;

const Main = styled.div`

`;

const Keg = styled.ul`
text-align: left;
display: flex;
flex-direction: column;
justify-content: left;
align-items: start;
background-color: lightgrey;
color: red;
padding: 16px;
padding-left: 32px;
`;

const Name = styled.li`
`;

let Details = styled.li`
`;

const Button = styled.button`

`;
