// Autogenerated using npm run gen NewKeg
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function NewKeg(){
  return (
    <Main>
      <h1>NewKeg Component Created Successfully</h1>
    </Main>
  );
}

export default NewKeg;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;

/*
* Copy to other files
* import NewKeg from './NewKeg';
* <NewKeg/>
*/


